[tf] all lowercase pygithub (Recidiviz/recidiviz-data#35567)
## Description of the change

saw this error during cloud build plan creation (realized i put this PR
up when comment terraform plan github thing wasn't working so i missed
this, my apologies)
```
Error: PYPI package "PyGithub" can only contain lowercase characters

  with google_composer_environment.default_v2,
  on cloud-composer.tf line 70, in resource "google_composer_environment" "default_v2":
  70:       pypi_packages = {
  71:         "us"                              = "==3.1.1"
  72:         "apache-airflow-providers-sftp"   = "==4.9.1"
  73:         "python-levenshtein"              = "==0.25.1"
  74:         "dateparser"                      = "==1.2.0"
  75:         "apache-airflow-providers-github" = "==2.6.2"
  76:         "PyGithub"                        = "==2.5.0"
  77:       }
```

## Type of change

> All pull requests must have at least one of the following labels
applied (otherwise the PR will fail):

| Label | Description |
|-----------------------------
|-----------------------------------------------------------------------------------------------------------
|
| Type: Bug | non-breaking change that fixes an issue |
| Type: Feature | non-breaking change that adds functionality |
| Type: Breaking Change | fix or feature that would cause existing
functionality to not work as expected |
| Type: Non-breaking refactor | change addresses some tech debt item or
prepares for a later change, but does not change functionality |
| Type: Configuration Change | adjusts configuration to achieve some end
related to functionality, development, performance, or security |
| Type: Dependency Upgrade | upgrades a project dependency - these
changes are not included in release notes |

## Related issues

Closes #XXXX

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [ ] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of
this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful
to a reviewer
- [ ] Potential security implications or infrastructural changes have
been considered, if relevant

GitOrigin-RevId: a286b0930d1ad6f9425642b05655c9f5058ba360