[Source Tables] Verify schema updates will be valid for all protected tables (Recidiviz/recidiviz-data#37590)
## Description of the change

This PR expands the `BigQuery Source Table Validation` to validate that
externally managed AND protected source tables match what is deployed to
BQ or only make changes that can safely be applied by our
`update_big_query_table_schemata` step.

Example script output (with some random local changes to demonstrate
various outputs):
```
(recidiviz-data) ageiduschek@Annas-MacBook-Pro-2 recidiviz-data % python -m recidiviz.tools.deploy.source_tables.check_source_table_schemas \
    --project-id recidiviz-staging \
    --source_table_type all
INFO:root:Checking [ALL] source tables for differences between what is deployed and
Performing source table dry run... |################################| 5432/5432
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/ageiduschek/src/recidiviz-data/recidiviz/tools/deploy/source_tables/check_source_table_schemas.py", line 74, in <module>
    check_source_table_schemas(
  File "/Users/ageiduschek/src/recidiviz-data/recidiviz/source_tables/update_big_query_table_schemas.py", line 234, in check_source_table_schemas
    raise ValueError(
ValueError: Found source table schema changes that are not safe to apply automatically. All changes found:

 ‼️Found the following externally managed tables with schemas defined in its YAML config
in recidiviz/source_tables/externally_managed that do not match the schema of the tables
defined in BigQuery. These tables are not managed by our standard source table update
process. If the YAML schema is incorrect, you will need to update it. If the YAML schema
is correct, you will need to update the process that generates this table to agree (or
manually update the table if there is no automatic process that generates it). Tables
with changes:

  * validation_results.validation_results (UPDATE_SCHEMA_WITH_DELETIONS)
    Deleted fields: ['run_id']

‼️Found the following managed tables with schemas derived from current code which have
changes that are NOT SAFE to apply automatically. If the new schema is correct, please
manually update the table to drop/rename the appropriate columns via DML statements in
the BigQuery UI (if you're unsure how to do this, ask in #platform-team). In order to
avoid breaking our currently deployed DAG, any manual changes should be applied right
before the deploy containing the relevant code changes that impacted the schema. If you
run any manual commands before the staging deploy, do not forget to add the analogous
commands to the next prod deploy checklist at https://go/deploy-checklist. Tables with
unsafe changes:

  * us_ar_raw_data.ADDRESS (UPDATE_SCHEMA_WITH_DELETIONS)
    Deleted fields: ['STREETNUMBER']
  * us_ar_raw_data_secondary.ADDRESS (UPDATE_SCHEMA_WITH_DELETIONS)
    Deleted fields: ['STREETNUMBER']
  * view_update_metadata.refresh_bq_dataset_tracker (UPDATE_SCHEMA_MODE_CHANGES)
    Changed type or mode: ['dataset_override_prefix']

✅ Found the following managed source table changes which have schema changes that can be
safely applied automatically via our update_big_query_table_schemata step. Tables with
changes:

  * us_ar_raw_data.ADMISSIONSUMMARY (UPDATE_SCHEMA_WITH_ADDITIONS)
    Added fields: ['SOME_NEW_FIELD']
  * us_ar_raw_data_secondary.ADMISSIONSUMMARY (UPDATE_SCHEMA_WITH_ADDITIONS)
    Added fields: ['SOME_NEW_FIELD']
  * us_ar_state.state_person_housing_status_period (UPDATE_SCHEMA_TYPE_CHANGES)
    Changed type or mode: ['housing_status_start_date']
  ... more states in here - omitted ...
  * us_tx_state.state_person_housing_status_period (UPDATE_SCHEMA_TYPE_CHANGES)
    Changed type or mode: ['housing_status_start_date']
  * us_ut_state.state_person_housing_status_period (UPDATE_SCHEMA_TYPE_CHANGES)
    Changed type or mode: ['housing_status_start_date']
```

## Type of change

> All pull requests must have at least one of the following labels
applied (otherwise the PR will fail):

| Label | Description |
|-----------------------------
|-----------------------------------------------------------------------------------------------------------
|
| Type: Bug | non-breaking change that fixes an issue |
| Type: Feature | non-breaking change that adds functionality |
| Type: Breaking Change | fix or feature that would cause existing
functionality to not work as expected |
| Type: Non-breaking refactor | change addresses some tech debt item or
prepares for a later change, but does not change functionality |
| Type: Configuration Change | adjusts configuration to achieve some end
related to functionality, development, performance, or security |
| Type: Dependency Upgrade | upgrades a project dependency - these
changes are not included in release notes |

## Related issues

Part of Recidiviz/recidiviz-data#37577

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of
this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful
to a reviewer
- [x] Potential security implications or infrastructural changes have
been considered, if relevant

GitOrigin-RevId: 36e6c226d16240565ad42c8313635939de51c9a8