Revert "[Autogenerated] Update Pipfile.lock (Recidiviz/recidiviz-data#36129)" (Recidiviz/recidiviz-data#36556)
## Description of the change

Reverts Recidiviz/recidiviz-data#36129 -- seems like opentelemetry's patches to the grpc library
don't play well with the latest grpc updates in google's client
libraries resulting in errors like
```
 TypeError: _InterceptorChannel.unary_unary() takes from 2 to 4 positional arguments but 5 were given
```
in the admin panel's flask app & k8s when trying to access secret
versions

## Type of change

> All pull requests must have at least one of the following labels
applied (otherwise the PR will fail):

| Label | Description |
|-----------------------------
|-----------------------------------------------------------------------------------------------------------
|
| Type: Bug | non-breaking change that fixes an issue |
| Type: Feature | non-breaking change that adds functionality |
| Type: Breaking Change | fix or feature that would cause existing
functionality to not work as expected |
| Type: Non-breaking refactor | change addresses some tech debt item or
prepares for a later change, but does not change functionality |
| Type: Configuration Change | adjusts configuration to achieve some end
related to functionality, development, performance, or security |
| Type: Dependency Upgrade | upgrades a project dependency - these
changes are not included in release notes |

## Related issues

Closes #XXXX

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [ ] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of
this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful
to a reviewer
- [ ] Potential security implications or infrastructural changes have
been considered, if relevant

GitOrigin-RevId: cbe007b3d50111a3fac37a20dcd3d3c9a6d86fd5